# Model settings
val_every: 1
model_checkpoint_interval: 5
seed: 1412
model:
  name: HelmehelmutoModel
  parameters:
    flatten_size: 128
    dropout_rate: 0.25
batch_size: 128
epochs: 30
loss_parameters: {}
optimizer:
  name: Adamax
  parameters:
    lr: 0.0003
lr_scheduler:
  name: CosineAnnealingLR
  parameters:
    T_max: 492700 # 100 * 4927 iterations

# Dataset settings
datasets:
  train:
    type: GalaxyDataset
    parameters:
      split: train
      normalize: true
      crop_size: 256
      resize_size: 64
      aug_chance: 0
      augmentations:
      root: "datasets"

  test:
    type: GalaxyDataset
    parameters:
      split: test
      normalize: true
      crop_size: 256
      resize_size: 64
      aug_chance: 0
      augmentations:
      root: "datasets"

  val:
    type: GalaxyDataset
    parameters:
      split: val
      normalize: true
      crop_size: 256
      resize_size: 64
      aug_chance: 0
      augmentations:
      root: "datasets"

  pred:
    type: GalaxyPredictDataset
    parameters:
      split: pred
      normalize: true
      crop_size: 256
      resize_size: 64
      root: "datasets"
